apiVersion: v1
kind: Service
metadata:
  name: {{ include "greetings.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app.kubernetes.io/name: {{ include "greetings.name" . }}
    helm.sh/chart: {{ include "greetings.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ include "greetings.name" . }}
    service: {{ include "greetings.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "greetings.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ include "greetings.name" . }}
